library(vegan);
x <- read.table("/home/rvlab/jobs2/demo@gmail.com/job45/softLagoonAbundance.csv", header = TRUE, sep=",",row.names=1);
ENV <- read.table("/home/rvlab/jobs2/demo@gmail.com/job45/softLagoonEnv.csv",header = TRUE, sep=",",row.names=1);
x <- t(x);
rownames(x) <- gsub("\\.","_",gsub(" ","_",rownames(x)));
vare.cca <- cca(x ~ maximumDepthInMeters+Temp, data=ENV);
cca1.plot<-plot(vare.cca, type="n");
text(vare.cca, dis="cn");
points(vare.cca, pch=21, col="red", bg="red", cex=0.5);
x<-x/rowSums(x);
x<-x[,order(colSums(x),decreasing=TRUE)];
#Extract list of top N Taxa;
N<-21;
taxa_list<-colnames(x)[1:N];
#remove "__Unknown__" and add it to others;
taxa_list<-taxa_list[!grepl("__Unknown__",taxa_list)];
N<-length(taxa_list);
new_x<-data.frame(x[,colnames(x) %in% taxa_list],Others=rowSums(x[,!colnames(x) %in% taxa_list]));
names<-gsub("\\.","_",gsub(" ","_",colnames(new_x)));
rownames(new_x) <- gsub("\\.","_",gsub(" ","_",rownames(new_x)));
sink("dataCCA.js");
cat("var freqData=[\n");
for (i in (1:dim(new_x)[1])){  
  cat(paste("{Samples:\'",rownames(new_x)[i],"\',",sep=""));
  cat(paste("freq:{",paste(paste(names,":",new_x[i,],sep=""),collapse=","),"},",sep=""));
  cat(paste("MDS:{",paste(paste(colnames(cca1.plot$sites),cca1.plot$sites[rownames(new_x)[i],],sep=":"),collapse=","),"}}\n",sep=""));
  if(i!=dim(new_x)[1]){cat(",")};
};
cat("];\n\n");
cat("var biplot=[\n");
for (i in (1:dim(cca1.plot$biplot)[1])){;
  cat(paste("{fact:{",paste(paste(colnames(cca1.plot$biplot),cca1.plot$biplot[rownames(cca1.plot$biplot)[i],],sep=":"),collapse=","),"}}\n",sep=""))  ;
  if(i!=dim(cca1.plot$biplot)[1]){cat(",")};
};
cat("];\n\n");
cat("var biplotLabels=[\n");
for (i in (1:dim(cca1.plot$biplot)[1])){;
  cat(paste("{fact:\"",paste(paste(rownames(cca1.plot$biplot)[i],sep=":"),collapse=","),"\"}\n",sep=""));
  if(i!=dim(cca1.plot$biplot)[1]){cat(",")};
};
cat("];\n");
sink();
