<?php

return array(
    'list' => array(
        'taxa2dist' => 'taxa2dist',
        'taxondive' => 'taxondive',
        'vegdist' => 'vegdist',
        'hclust'    =>  'hclust',
        'bict' => 'bict',
        'pca' => 'pca',
        'cca' => 'cca',
        'anosim' => 'anosim',
        'anova' => 'anova',
        'permanova' => 'permanova',
        'mantel' => 'mantel',
        'metamds' => 'metamds',
        'cca_visual' => 'cca_visual',
        'mapping_tools_visual' => 'mapping_tools_visual',
        'mapping_tools_div_visual' => 'mapping_tools_div_visual',
        'heatcloud' => 'heatcloud',
        'phylobar' => 'phylobar',
        'second_metamds' => '2nd stage MDS',
        'metamds_visual' => 'metamds_visual',
        'radfit' => 'radfit',
        'bioenv' => 'bioenv',
        'simper' => 'simper',
        'regression' => 'regression',
        'parallel_taxa2dist' => 'Parallel taxa2dist',
        'parallel_postgres_taxa2dist' => 'Parallel taxa2dist postgres',
        'parallel_anosim' => 'Parallel anosim',
        'parallel_mantel' => 'Parallel mantel',
        'parallel_taxa2taxon' => 'Parallel taxa2dist to taxondive',
        'parallel_permanova' => 'Parallel permanova',
        'parallel_bioenv' => 'Parallel bioenv',
        'parallel_simper' => 'Parallel simper',
        'convert2r' => 'Convert to R',
    ),
);